export const UPDATE_SEARCH_KEY = "UPDATE_SEARCH_KEY";
export const FETCH_USER = "FETCH_USER";
export const FETCH_REPOSITORIES = "FETCH_REPOSITORIES";
export const FETCH_ORGANIZATIONS = "FETCH_ORGANIZATIONS";
export const FETCH_FOLLOWERS = "FETCH_FOLLOWERS";
export const FETCH_FOLLOWINGS = "FETCH_FOLLOWINGS";
export const SELECT_REPOSITORY = "SELECT_REPOSITORY";
